In [18]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor

from sklearn.datasets import load_boston
boston = load_boston()
X = boston.data
y = boston.target

In [19]:
rf = RandomForestRegressor(random_state=2020)
rf

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
                      max_features='auto', max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, n_estimators='warn',
                      n_jobs=None, oob_score=False, random_state=2020,
                      verbose=0, warm_start=False)

In [20]:
rf.fit(X, y)
# Random forests just split your data in random, uncorrelated ways

/opt/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
                      max_features='auto', max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, n_estimators=10,
                      n_jobs=None, oob_score=False, random_state=2020,
                      verbose=0, warm_start=False)

In [26]:
rf.estimators_

[DecisionTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, min_impurity_decrease=0.0,
                       min_impurity_split=None, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       presort=False, random_state=2088543072, splitter='best'),
 DecisionTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, min_impurity_decrease=0.0,
                       min_impurity_split=None, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       presort=False, random_state=639299976, splitter='best'),
 DecisionTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, min_impurity_decrease=0.0,
                       min_impurity_split=None, min_samples_leaf=1,
                       min_samples_split=2,

In [21]:
rf.estimators_[0].predict(X[:1])

array([29.4])

In [22]:
[tree.predict(X[:1]) for tree in rf.estimators_]

[array([29.4]),
 array([24.]),
 array([24.]),
 array([30.1]),
 array([24.]),
 array([24.]),
 array([24.]),
 array([24.]),
 array([24.]),
 array([24.6])]

In [23]:
np.mean([tree.predict(X[:1]) for tree in rf.estimators_])

25.21

In [25]:
rf.predict(X[:1])

# When you predict with the random forest
# you're just predicting each individual decision tree and averaging their values together
# Just takes each individual tree, makes the prediction, and then averages them all together
# Decision trees are weak predictors in useful ways

array([25.21])

In [29]:
# How do you tune a random forest?

rf.get_params()
# Random forests have some interesting parameters!
# All comes down to how you grow your trees
# Max_depth - how many levels of splitting/branches
# Shallower your trees, the more likely you are to be underfit
# Deeper your trees, the more likely you are to be overfit
# Max Features - maximum number of columns that it accepts. Typically a decimal. .6 is 60% of your columns. More of a top down.
# Min samples per leaf - minimum number of samples that have to be there. More bottom up approach.
# N_estimators - number of trees!

{'bootstrap': True,
 'criterion': 'mse',
 'max_depth': None,
 'max_features': 'auto',
 'max_leaf_nodes': None,
 'min_impurity_decrease': 0.0,
 'min_impurity_split': None,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 10,
 'n_jobs': None,
 'oob_score': False,
 'random_state': 2020,
 'verbose': 0,
 'warm_start': False}

In [32]:
rf.score(X, y)
# This is a heavily overfit random forest
# The default value is for the min_samples to be 1. This is not really the best choice

0.9697998600424886

In [34]:
# Grid search!
# Like a gigantic cannon
# A great way to exhaustively search parameters

from sklearn.model_selection import GridSearchCV

In [35]:
?GridSearchCV
# Lots of different parameters for GridSearchCV, check em out

In [38]:
from sklearn.metrics import mean_squared_error, make_scorer

loss_function = make_scorer(mean_squared_error, greater_is_better=False)
# Normally when you do cross validation it returns R2
# Sometimes you'd want to have a loss function
# Greater is better is a default... but you want to the lowest possible mean squared error

In [40]:
?make_scorer

In [41]:
# Firing out everything and seeing what your best results are
params = {
    'n_estimators': [5, 10, 25, 50],
    'max_features': [.03, 0.4, 0.5, 0.6],
    'min_samples_leaf' : [5, 10, 15]
}

In [42]:
grid = GridSearchCV(estimator=rf, param_grid=params, scoring=loss_function, cv=5)
# Take our random forest, test out all paramaeters, use our loss function and do 5 fold cross validation

In [43]:
grid.fit(X,y)

/opt/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_search.py:814: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


GridSearchCV(cv=5, error_score='raise-deprecating',
             estimator=RandomForestRegressor(bootstrap=True, criterion='mse',
                                             max_depth=None,
                                             max_features='auto',
                                             max_leaf_nodes=None,
                                             min_impurity_decrease=0.0,
                                             min_impurity_split=None,
                                             min_samples_leaf=1,
                                             min_samples_split=2,
                                             min_weight_fraction_leaf=0.0,
                                             n_estimators=10, n_jobs=None,
                                             oob_score=False, random_state=2020,
                                             verbose=0, warm_start=False),
             iid='warn', n_jobs=None,
             param_grid={'max_features': [0.03, 0.4, 0.5, 0.

In [46]:
grid.best_params_
# What combination gave you the best score

{'max_features': 0.6, 'min_samples_leaf': 5, 'n_estimators': 25}

In [50]:
grid_results = pd.DataFrame(grid.cv_results_)
# A big dictionary
# Useful to turn into a dataframe

In [53]:
grid_results
# Results from every single permutation
# Effectively create a data set for the fitting of your model to see how things perform under different conditions

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
0        0.008188      0.002976         0.000880        0.000192   
1        0.010707      0.000497         0.000850        0.000061   
2        0.024029      0.000933         0.001418        0.000109   
3        0.050411      0.002373         0.002380        0.000129   
4        0.005582      0.000839         0.000625        0.000031   
5        0.009899      0.000242         0.001005        0.000300   
6        0.024342      0.001090         0.001591        0.000302   
7        0.050071      0.003275         0.002435        0.000289   
8        0.004995      0.000257         0.000593        0.000020   
9        0.009674      0.000106         0.000898        0.000120   
10       0.023389      0.000575         0.001339        0.000047   
11       0.045418      0.000815         0.002364        0.000341   
12       0.006339      0.000091         0.000611        0.000028   
13       0.013695      0.001935         0.000830        0.000036   
14       0.031178      0.001593         0.001893        0.000632   
15       0.060968      0.001447         0.002329        0.000093   
16       0.006349      0.000307         0.000686        0.000154   
17       0.011788      0.000368         0.000832        0.000077   
18       0.028886      0.000489         0.001412        0.000071   
19       0.056321      0.000769         0.002226        0.000091   
20       0.006105      0.000319         0.000664        0.000112   
21       0.011237      0.000366         0.000803        0.000052   
22       0.027551      0.000828         0.001390        0.000123   
23       0.054738      0.001309         0.002192        0.000060   
24       0.007204      0.000575         0.000745        0.000079   
25       0.013126      0.000528         0.000890        0.000123   
26       0.032124      0.000755         0.001501        0.000126   
27       0.064187      0.002175         0.002401        0.000106   
28       0.006747      0.000426         0.000713        0.000199   
29       0.012463      0.000579         0.000857        0.000060   
30       0.030330      0.001550         0.001477        0.000224   
31       0.061274      0.003233         0.002451        0.000257   
32       0.006035      0.000266         0.000623        0.000058   
33       0.012295      0.000888         0.000811        0.000021   
34       0.029344      0.001239         0.001301        0.000024   
35       0.057487      0.001164         0.002259        0.000149   
36       0.007156      0.000342         0.000688        0.000154   
37       0.014505      0.000772         0.000855        0.000030   
38       0.034454      0.000601         0.001503        0.000102   
39       0.067979      0.001131         0.002449        0.000149   
40       0.006984      0.000442         0.000663        0.000076   
41       0.013149      0.000527         0.000828        0.000058   
42       0.031930      0.001316         0.001546        0.000103   
43       0.063335      0.001818         0.002636        0.000421   
44       0.006367      0.000312         0.000625        0.000067   
45       0.011791      0.000238         0.000778        0.000006   
46       0.029409      0.000439         0.001413        0.000148   
47       0.059468      0.002818         0.002400        0.000461   

   param_max_features param_min_samples_leaf param_n_estimators  \
0                0.03                      5                  5   
1                0.03                      5                 10   
2                0.03                      5                 25   
3                0.03                      5                 50   
4                0.03                     10                  5   
5                0.03                     10                 10   
6                0.03                     10                 25   
7                0.03                     10                 50   
8                0.03                     15                  5   
9

In [57]:
grid_results.sort_values(by='rank_test_score')
# The differences between the 1st, 2nd, 3rd, 4th might be a fraction of a percent

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
38       0.034454      0.000601         0.001503        0.000102   
39       0.067979      0.001131         0.002449        0.000149   
37       0.014505      0.000772         0.000855        0.000030   
27       0.064187      0.002175         0.002401        0.000106   
15       0.060968      0.001447         0.002329        0.000093   
14       0.031178      0.001593         0.001893        0.000632   
26       0.032124      0.000755         0.001501        0.000126   
43       0.063335      0.001818         0.002636        0.000421   
42       0.031930      0.001316         0.001546        0.000103   
13       0.013695      0.001935         0.000830        0.000036   
25       0.013126      0.000528         0.000890        0.000123   
31       0.061274      0.003233         0.002451        0.000257   
41       0.013149      0.000527         0.000828        0.000058   
36       0.007156      0.000342         0.000688        0.000154   
19       0.056321      0.000769         0.002226        0.000091   
30       0.030330      0.001550         0.001477        0.000224   
18       0.028886      0.000489         0.001412        0.000071   
40       0.006984      0.000442         0.000663        0.000076   
47       0.059468      0.002818         0.002400        0.000461   
22       0.027551      0.000828         0.001390        0.000123   
46       0.029409      0.000439         0.001413        0.000148   
21       0.011237      0.000366         0.000803        0.000052   
35       0.057487      0.001164         0.002259        0.000149   
17       0.011788      0.000368         0.000832        0.000077   
23       0.054738      0.001309         0.002192        0.000060   
12       0.006339      0.000091         0.000611        0.000028   
44       0.006367      0.000312         0.000625        0.000067   
34       0.029344      0.001239         0.001301        0.000024   
24       0.007204      0.000575         0.000745        0.000079   
45       0.011791      0.000238         0.000778        0.000006   
29       0.012463      0.000579         0.000857        0.000060   
20       0.006105      0.000319         0.000664        0.000112   
16       0.006349      0.000307         0.000686        0.000154   
33       0.012295      0.000888         0.000811        0.000021   
28       0.006747      0.000426         0.000713        0.000199   
0        0.008188      0.002976         0.000880        0.000192   
32       0.006035      0.000266         0.000623        0.000058   
4        0.005582      0.000839         0.000625        0.000031   
1        0.010707      0.000497         0.000850        0.000061   
2        0.024029      0.000933         0.001418        0.000109   
5        0.009899      0.000242         0.001005        0.000300   
3        0.050411      0.002373         0.002380        0.000129   
6        0.024342      0.001090         0.001591        0.000302   
8        0.004995      0.000257         0.000593        0.000020   
7        0.050071      0.003275         0.002435        0.000289   
9        0.009674      0.000106         0.000898        0.000120   
10       0.023389      0.000575         0.001339        0.000047   
11       0.045418      0.000815         0.002364        0.000341   

   param_max_features param_min_samples_leaf param_n_estimators  \
38                0.6                      5                 25   
39                0.6                      5                 50   
37                0.6                      5                 10   
27                0.5                      5                 50   
15                0.4                      5                 50   
14                0.4                      5                 25   
26                0.5                      5                 25   
43                0.6                     10                 50   
42                0.6                     10                 25   
1

In [59]:
grid_results.groupby('param_min_samples_leaf')['mean_test_score'].mean()
# 5 looks like it gives consistently better results
# In real life these numbers are positive.
# Makes it negative automatically to work well with other models.

param_min_samples_leaf
5    -24.666358
10   -27.497689
15   -30.374537
Name: mean_test_score, dtype: float64

In [61]:
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler

pipe = make_pipeline(StandardScaler(), rf)

In [62]:
pipe

Pipeline(memory=None,
         steps=[('standardscaler',
                 StandardScaler(copy=True, with_mean=True, with_std=True)),
                ('randomforestregressor',
                 RandomForestRegressor(bootstrap=True, criterion='mse',
                                       max_depth=None, max_features='auto',
                                       max_leaf_nodes=None,
                                       min_impurity_decrease=0.0,
                                       min_impurity_split=None,
                                       min_samples_leaf=1, min_samples_split=2,
                                       min_weight_fraction_leaf=0.0,
                                       n_estimators=10, n_jobs=None,
                                       oob_score=False, random_state=2020,
                                       verbose=0, warm_start=False))],
         verbose=False)

In [63]:
pipe.steps
# You can grid search a pipeline
# You can grid search multiple steps

[('standardscaler', StandardScaler(copy=True, with_mean=True, with_std=True)),
 ('randomforestregressor',
  RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
                        max_features='auto', max_leaf_nodes=None,
                        min_impurity_decrease=0.0, min_impurity_split=None,
                        min_samples_leaf=1, min_samples_split=2,
                        min_weight_fraction_leaf=0.0, n_estimators=10,
                        n_jobs=None, oob_score=False, random_state=2020,
                        verbose=0, warm_start=False))]

In [64]:
params = {
    'randomforestregressor__min_samples_leaf': [5, 10, 15],
    # You type in the name of the step, two underscores, and then the name of the parameter
    'randomforestregressor__max_features': [0.4, 0.5, 0.6]
}

In [65]:
grid = GridSearchCV(estimator=pipe, param_grid=params, scoring=loss_function, cv=10)
# Once you do that it works exactly the same way

In [67]:
grid.fit(X,y)

/opt/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_search.py:814: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


GridSearchCV(cv=10, error_score='raise-deprecating',
             estimator=Pipeline(memory=None,
                                steps=[('standardscaler',
                                        StandardScaler(copy=True,
                                                       with_mean=True,
                                                       with_std=True)),
                                       ('randomforestregressor',
                                        RandomForestRegressor(bootstrap=True,
                                                              criterion='mse',
                                                              max_depth=None,
                                                              max_features='auto',
                                                              max_leaf_nodes=None,
                                                              min_impurity_decrease=0.0,
                                                              min_impurity_split