In [22]:
import pandas as pd
import numpy as np

In [23]:
df = pd.read_csv('/Users/aoifeduna/AoifeRepo/aoiferepo/Lectures/Unit3/data/housing.csv')

In [24]:
df.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  TAX  PTRATIO  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

        B  LSTAT  PRICE  
0  396.90   4.98   24.0  
1  396.90   9.14   21.6  
2  392.83   4.03   34.7  
3  394.63   2.94   33.4  
4  396.90   5.33   36.2

In [25]:
X = df.drop('PRICE', axis=1)
y = df['PRICE']

from sklearn.linear_model import LinearRegression

lreg= LinearRegression()

In [26]:
lreg.fit(X,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [27]:
lreg.coef_

array([-1.08011358e-01,  4.64204584e-02,  2.05586264e-02,  2.68673382e+00,
       -1.77666112e+01,  3.80986521e+00,  6.92224640e-04, -1.47556685e+00,
        3.06049479e-01, -1.23345939e-02, -9.52747232e-01,  9.31168327e-03,
       -5.24758378e-01])

In [28]:
np.sum(lreg.coef_**2)
# This is why you need to scale your data. The penalty will just keep getting bigger and bigger.

340.8546317880245

In [29]:
train = pd.read_csv('/Users/aoifeduna/AoifeRepo/aoiferepo/Lectures/Unit3/data/iowa_housing/train.csv')

In [30]:
test = pd.read_csv('/Users/aoifeduna/AoifeRepo/aoiferepo/Lectures/Unit3/data/iowa_housing/test.csv')

In [31]:
train.isnull().sum()

Id               0
MSSubClass       0
MSZoning         0
LotArea          0
Neighborhood     0
OverallQual      0
OverallCond      0
YearBuilt        0
GrLivArea        0
1stFlrSF         0
2ndFlrSF         0
GrLivArea.1      0
FullBath         0
HalfBath         0
GarageType      81
GarageYrBlt     81
GarageFinish    81
GarageCars       0
SalePrice        0
dtype: int64

In [32]:
y = np.log(train['SalePrice'])
train.drop('SalePrice', axis=1, inplace=True)
test_id = test['Id']
train.drop('Id', axis=1, inplace=True)
test.drop('Id', axis=1, inplace=True)
# Copying and pasting from the lab from class 14

In [33]:
train_empty = train.loc[:, train.isnull().sum() > 0]
# grab the columns
cols = train_empty.columns.tolist()
# fill with the appropriate value  -- NA, Other, could also work
train[['GarageType', 'GarageFinish']] = train[['GarageType', 'GarageFinish']].fillna('None')
test[['GarageType', 'GarageFinish']]  = test[['GarageType', 'GarageFinish']].fillna('None')

# we'll use this for GarageYrBlt since it's a numeric column
train['GarageYrBlt'].fillna(0, inplace=True)
test['GarageYrBlt'].fillna(0, inplace=True)

# finding the values to use in the training set
ms_mode   = train['MSZoning'].mode()[0]
gcarsmean = train['GarageCars'].mean()

# and applying them to the test set
test['MSZoning'].fillna(ms_mode, inplace=True)
test['GarageCars'].fillna(gcarsmean, inplace=True)

# Final solution code from the lab... just to fill in null values

In [34]:
train['MSSubClass'] = train['MSSubClass'].astype(str)
test['MSSubClass']  = test['MSSubClass'].astype(str)
# Reclassifying MSSubClass as a string so that it's not one hot encoded

In [35]:
# The standard with nominal variables is to one hot encode them
# E.g. seasons, time

In [36]:
conda install -c conda-forge category_encoders

Solving environment: done

# All requested packages already installed.


Note: you may need to restart the kernel to use updated packages.


In [37]:
from sklearn.preprocessing import StandardScaler
from category_encoders import OrdinalEncoder, OneHotEncoder
from sklearn.linear_model import Ridge, Lasso
from sklearn.model_selection import cross_val_score
from sklearn.pipeline import make_pipeline

In [41]:
sc = StandardScaler()

In [42]:
sc.fit_transform(X)

array([[-0.41978194,  0.28482986, -1.2879095 , ..., -1.45900038,
         0.44105193, -1.0755623 ],
       [-0.41733926, -0.48772236, -0.59338101, ..., -0.30309415,
         0.44105193, -0.49243937],
       [-0.41734159, -0.48772236, -0.59338101, ..., -0.30309415,
         0.39642699, -1.2087274 ],
       ...,
       [-0.41344658, -0.48772236,  0.11573841, ...,  1.17646583,
         0.44105193, -0.98304761],
       [-0.40776407, -0.48772236,  0.11573841, ...,  1.17646583,
         0.4032249 , -0.86530163],
       [-0.41500016, -0.48772236,  0.11573841, ...,  1.17646583,
         0.44105193, -0.66905833]])

In [43]:
sc.mean_

array([3.61352356e+00, 1.13636364e+01, 1.11367787e+01, 6.91699605e-02,
       5.54695059e-01, 6.28463439e+00, 6.85749012e+01, 3.79504269e+00,
       9.54940711e+00, 4.08237154e+02, 1.84555336e+01, 3.56674032e+02,
       1.26530632e+01])

In [46]:
sc.var_

array([7.38403597e+01, 5.42861840e+02, 4.69714297e+01, 6.43854770e-02,
       1.34010989e-02, 4.92695216e-01, 7.90792473e+02, 4.42525226e+00,
       7.56665313e+01, 2.83486236e+04, 4.67772630e+00, 8.31828042e+03,
       5.08939794e+01])

In [49]:
# Later on you can call transform and it will transform the new data
# based off these values
# When you call fittransform multiple times it will transform it based on the same values

sc.transform(X_test)
# It will scale the data according to the preceding fitted values

NameError: name 'X_test' is not defined

In [50]:
ore = OrdinalEncoder()
# Initializing the ordinal encoder

In [51]:
ore.fit_transform(train)
# If you don't specify anything, it will ordinal encode every single categorical column
# Ordinal encoders return in a data frame, not a numpyarray


MSSubClass  MSZoning  LotArea  Neighborhood  OverallQual  OverallCond  \
0              1         1     8450             1            7            5   
1              2         1     9600             2            6            8   
2              1         1    11250             1            7            5   
3              3         1     9550             3            7            5   
4              1         1    14260             4            8            5   
...          ...       ...      ...           ...          ...          ...   
1455           1         1     7917            18            6            5   
1456           2         1    13175             7            6            6   
1457           3         1     9042             3            7            9   
1458           2         1     9717            12            5            6   
1459           2         1     9937            16            5            6   

      YearBuilt  GrLivArea  1stFlrSF  2ndFlrSF  GrLivArea.1  FullBath  \
0          2003       1710       856       854         1710         2   
1          1976       1262      1262         0         1262         2   
2          2001       1786       920       866         1786         2   
3          1915       1717       961       756         1717         1   
4          2000       2198      1145      1053         2198         2   
...         ...        ...       ...       ...          ...       ...   
1455       1999       1647       953       694         1647         2   
1456       1978       2073      2073         0         2073         2   
1457       1941       2340      1188      1152         2340         2   
1458       1950       1078      1078         0         1078         1   
1459       1965       1256      1256         0         1256         1   

      HalfBath  GarageType  GarageYrBlt  GarageFinish  GarageCars  
0            1           1       2003.0             1           2  
1            0           1       1976.0             1           2  
2            1           1       2001.0             1           2  
3            0           2       1998.0             2           3  
4            1           1       2000.0             1           3  
...        ...         ...          ...           ...         ...  
1455         1           1       1999.0             1           2  
1456         0           1       1978.0             2           2  
1457         0           1       1941.0             1           1  
1458         0           1       1950.0             2           1  
1459         1           1       1965.0             3           1  

[1460 rows x 17 columns]

In [52]:
# If you want to be more specific (and not just pass in the entire df)
# you have to create two dictionaries

garage_mapping = {
    'None': 1,
    'Unf': 2,
    'RFn': 3,
    'Fin': 4
}
# Basically, map this to that, and this to that 

In [53]:
col_mapping = {
    # This dictionary is always going to have the same setup
    # You're going to have two keys, column, and then the dictionary mapping
    'col': 'GarageFinish',
    'mapping': garage_mapping
}

In [55]:
ore = OrdinalEncoder(cols=['GarageFinish'], mapping=[col_mapping])

In [56]:
ore.fit_transform(train)
# Now, we've only encoded this column
# The other columns are untouched

MSSubClass MSZoning  LotArea Neighborhood  OverallQual  OverallCond  \
0            60       RL     8450      CollgCr            7            5   
1            20       RL     9600      Veenker            6            8   
2            60       RL    11250      CollgCr            7            5   
3            70       RL     9550      Crawfor            7            5   
4            60       RL    14260      NoRidge            8            5   
...         ...      ...      ...          ...          ...          ...   
1455         60       RL     7917      Gilbert            6            5   
1456         20       RL    13175       NWAmes            6            6   
1457         70       RL     9042      Crawfor            7            9   
1458         20       RL     9717        NAmes            5            6   
1459         20       RL     9937      Edwards            5            6   

      YearBuilt  GrLivArea  1stFlrSF  2ndFlrSF  GrLivArea.1  FullBath  \
0          2003       1710       856       854         1710         2   
1          1976       1262      1262         0         1262         2   
2          2001       1786       920       866         1786         2   
3          1915       1717       961       756         1717         1   
4          2000       2198      1145      1053         2198         2   
...         ...        ...       ...       ...          ...       ...   
1455       1999       1647       953       694         1647         2   
1456       1978       2073      2073         0         2073         2   
1457       1941       2340      1188      1152         2340         2   
1458       1950       1078      1078         0         1078         1   
1459       1965       1256      1256         0         1256         1   

      HalfBath GarageType  GarageYrBlt  GarageFinish  GarageCars  
0            1     Attchd       2003.0             3           2  
1            0     Attchd       1976.0             3           2  
2            1     Attchd       2001.0             3           2  
3            0     Detchd       1998.0             2           3  
4            1     Attchd       2000.0             3           3  
...        ...        ...          ...           ...         ...  
1455         1     Attchd       1999.0             3           2  
1456         0     Attchd       1978.0             2           2  
1457         0     Attchd       1941.0             3           1  
1458         0     Attchd       1950.0             2           1  
1459         1     Attchd       1965.0             4           1  

[1460 rows x 17 columns]

In [57]:
ohe = OneHotEncoder()
# For all of these things there are always going to be arguments called cols
# You specify what columns you want things to apply to

In [58]:
ohe.fit_transform(train)
# See? This one hot encoded everything
# Getdummies can be a bit finicky, this is easier
# Note that we're NOT changing the underlying data set
# If we want to do that, we'd have to re-save it. train = ore.fit_transform(train), etc.

MSSubClass_1  MSSubClass_2  MSSubClass_3  MSSubClass_4  MSSubClass_5  \
0                1             0             0             0             0   
1                0             1             0             0             0   
2                1             0             0             0             0   
3                0             0             1             0             0   
4                1             0             0             0             0   
...            ...           ...           ...           ...           ...   
1455             1             0             0             0             0   
1456             0             1             0             0             0   
1457             0             0             1             0             0   
1458             0             1             0             0             0   
1459             0             1             0             0             0   

      MSSubClass_6  MSSubClass_7  MSSubClass_8  MSSubClass_9  MSSubClass_10  \
0                0             0             0             0              0   
1                0             0             0             0              0   
2                0             0             0             0              0   
3                0             0             0             0              0   
4                0             0             0             0              0   
...            ...           ...           ...           ...            ...   
1455             0             0             0             0              0   
1456             0             0             0             0              0   
1457             0             0             0             0              0   
1458             0             0             0             0              0   
1459             0             0             0             0              0   

      ...  GarageType_4  GarageType_5  GarageType_6  GarageType_7  \
0     ...             0             0             0             0   
1     ...             0             0             0             0   
2     ...             0             0             0             0   
3     ...             0             0             0             0   
4     ...             0             0             0             0   
...   ...           ...           ...           ...           ...   
1455  ...             0             0             0             0   
1456  ...             0             0             0             0   
1457  ...             0             0             0             0   
1458  ...             0             0             0             0   
1459  ...             0             0             0             0   

      GarageYrBlt  GarageFinish_1  GarageFinish_2  GarageFinish_3  \
0          2003.0               1               0               0   
1          1976.0               1               0               0   
2          2001.0               1               0               0   
3          1998.0               0               1               0   
4          2000.0               1               0               0   
...           ...             ...             ...             ...   
1455       1999.0               1               0               0   
1456       1978.0               0               1               0   
1457       1941.0               1               0               0   
1458       1950.0               0               1               0   
1459       1965.0               0               0               1   

      GarageFinish_4  GarageCars  
0                  0           2  
1                  0           2  
2                  0           2  
3                  0           3  
4                  0           3  
...              ...         ...  
1455               0           2  
1456               0           2  
1457               0           1  
1458               0           1  
1459               0           1  

[1460 rows x 68 columns]

In [59]:
ohe.transform(test)
# This will transform the test set based on the values of the training set
# This handles all the details for you automatically

MSSubClass_1  MSSubClass_2  MSSubClass_3  MSSubClass_4  MSSubClass_5  \
0                0             1             0             0             0   
1                0             1             0             0             0   
2                1             0             0             0             0   
3                1             0             0             0             0   
4                0             0             0             0             0   
...            ...           ...           ...           ...           ...   
1454             0             0             0             0             0   
1455             0             0             0             0             0   
1456             0             1             0             0             0   
1457             0             0             0             0             0   
1458             1             0             0             0             0   

      MSSubClass_6  MSSubClass_7  MSSubClass_8  MSSubClass_9  MSSubClass_10  \
0                0             0             0             0              0   
1                0             0             0             0              0   
2                0             0             0             0              0   
3                0             0             0             0              0   
4                0             0             1             0              0   
...            ...           ...           ...           ...            ...   
1454             0             0             0             0              0   
1455             0             0             0             0              0   
1456             0             0             0             0              0   
1457             0             0             0             0              1   
1458             0             0             0             0              0   

      ...  GarageType_4  GarageType_5  GarageType_6  GarageType_7  \
0     ...             0             0             0             0   
1     ...             0             0             0             0   
2     ...             0             0             0             0   
3     ...             0             0             0             0   
4     ...             0             0             0             0   
...   ...           ...           ...           ...           ...   
1454  ...             0             1             0             0   
1455  ...             1             0             0             0   
1456  ...             0             0             0             0   
1457  ...             0             1             0             0   
1458  ...             0             0             0             0   

      GarageYrBlt  GarageFinish_1  GarageFinish_2  GarageFinish_3  \
0          1961.0               0               1               0   
1          1958.0               0               1               0   
2          1997.0               0               0               1   
3          1998.0               0               0               1   
4          1992.0               1               0               0   
...           ...             ...             ...             ...   
1454          0.0               0               0               0   
1455       1970.0               0               1               0   
1456       1960.0               0               1               0   
1457          0.0               0               0               0   
1458       1993.0               0               0               1   

      GarageFinish_4  GarageCars  
0                  0         1.0  
1                  0         1.0  
2                  0         2.0  
3                  0         2.0  
4                  0         2.0  
...              ...         ...  
1454               1         0.0  
1455               0         1.0  
1456               0         2.0  
1457               1         0.0  
1458               0         3.0  

[1459 rows x 68 columns]

In [60]:
# You want to ordinally encode first to get everything numeric
# THEN scale

In [61]:
# When we're calling ordinal encoder.fit_transform, etc... it's not being stored

In [62]:
pipe = make_pipeline(ore, ohe, sc)
# Just specify what you want to do

In [63]:
pipe

Pipeline(memory=None,
         steps=[('ordinalencoder',
                 OrdinalEncoder(cols=['GarageFinish'], drop_invariant=False,
                                handle_missing='value', handle_unknown='value',
                                mapping=[{'col': 'GarageFinish',
                                          'mapping': {'Fin': 4, 'None': 1,
                                                      'RFn': 3, 'Unf': 2}}],
                                return_df=True, verbose=0)),
                ('onehotencoder',
                 OneHotEncoder(cols=['MSSubClass', 'MSZoning', 'Neighborhood',
                                     'GarageType', 'GarageFinish'],
                               drop_invariant=False, handle_missing='value',
                               handle_unknown='value', return_df=True,
                               use_cat_names=False, verbose=0)),
                ('standardscaler',
                 StandardScaler(copy=True, with_mean=True, with_std=True))],
  

In [64]:
pipe.fit(train)

Pipeline(memory=None,
         steps=[('ordinalencoder',
                 OrdinalEncoder(cols=['GarageFinish'], drop_invariant=False,
                                handle_missing='value', handle_unknown='value',
                                mapping=[{'col': 'GarageFinish',
                                          'mapping': {'Fin': 4, 'None': 1,
                                                      'RFn': 3, 'Unf': 2}}],
                                return_df=True, verbose=0)),
                ('onehotencoder',
                 OneHotEncoder(cols=['MSSubClass', 'MSZoning', 'Neighborhood',
                                     'GarageType', 'GarageFinish'],
                               drop_invariant=False, handle_missing='value',
                               handle_unknown='value', return_df=True,
                               use_cat_names=False, verbose=0)),
                ('standardscaler',
                 StandardScaler(copy=True, with_mean=True, with_std=True))],
  

In [65]:
pipe.transform(test)
# Transform the test set based on the training set
# Gives us the encoded version of our test set based on the training set
# It ordinally encodes, one hot encodes, and scales the data all in one swoop
# Amazing!
# Different models are encoded differently. E.g. Random forest is encoded different from a linear model
# Just create different pipelines for your different models and just use fit and transform for each one


array([[-0.50748065,  1.31296634, -0.20701967, ..., -0.56363954,
        -0.24235968, -1.02685765],
       [-0.50748065,  1.31296634, -0.20701967, ..., -0.56363954,
        -0.24235968, -1.02685765],
       [ 1.9705185 , -0.76163415, -0.20701967, ...,  1.77418355,
        -0.24235968,  0.31172464],
       ...,
       [-0.50748065,  1.31296634, -0.20701967, ..., -0.56363954,
        -0.24235968,  0.31172464],
       [-0.50748065, -0.76163415, -0.20701967, ..., -0.56363954,
         4.12609881, -2.36543995],
       [ 1.9705185 , -0.76163415, -0.20701967, ...,  1.77418355,
        -0.24235968,  1.65030694]])

In [67]:
# You can also finish off a pipeline with a predictor
ridge = Ridge()
pipe = make_pipeline(ore, ohe, sc, ridge)
# You can do as many transformers as you'd like
# But the estimator HAS to be the last thing

In [69]:
# If it has the fittransform method it's a transformer
# If it has a predictor method it's an estimator
# Since ridge is the last thing you need a y too!!!
pipe.fit(train, y)


Pipeline(memory=None,
         steps=[('ordinalencoder',
                 OrdinalEncoder(cols=['GarageFinish'], drop_invariant=False,
                                handle_missing='value', handle_unknown='value',
                                mapping=[{'col': 'GarageFinish',
                                          'mapping': {'Fin': 4, 'None': 1,
                                                      'RFn': 3, 'Unf': 2}}],
                                return_df=True, verbose=0)),
                ('onehotencoder',
                 OneHotEncoder(cols=['MSSubClass', 'MSZoning', 'Neighborhood',
                                     'GarageType', 'GarageFinish'],
                               drop_invariant=False, handle_missing='value',
                               handle_unknown='value', return_df=True,
                               use_cat_names=False, verbose=0)),
                ('standardscaler',
                 StandardScaler(copy=True, with_mean=True, with_std=True)),
   

In [72]:
pipe.predict(test)
# Now this will predict the value of test using the fitted and transformed training data
# This is a convenient way to blend a lot of different methods together

array([11.67645012, 11.94330452, 12.04733841, ..., 11.92336206,
       11.6755666 , 12.33082765])