In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('/Users/aoifeduna/AoifeRepo/aoiferepo/Lectures/Unit3/data/housing.csv')

In [3]:
df.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  TAX  PTRATIO  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

        B  LSTAT  PRICE  
0  396.90   4.98   24.0  
1  396.90   9.14   21.6  
2  392.83   4.03   34.7  
3  394.63   2.94   33.4  
4  396.90   5.33   36.2

In [5]:
from sklearn.linear_model import LinearRegression
lreg = LinearRegression()

X = df.drop('PRICE', axis=1)
y = df['PRICE']

lreg.fit(X, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [6]:
lreg.coef_
# You take these coefficients and multiply them by each of your columns to get your predictions

array([-1.08011358e-01,  4.64204584e-02,  2.05586264e-02,  2.68673382e+00,
       -1.77666112e+01,  3.80986521e+00,  6.92224640e-04, -1.47556685e+00,
        3.06049479e-01, -1.23345939e-02, -9.52747232e-01,  9.31168327e-03,
       -5.24758378e-01])

In [10]:
np.sum(X*lreg.coef_, axis=1) + lreg.intercept_
# This is basically how linear regression works
# Neural networks basically do the same thing!
# They just use a loooot more computation
# But if you strip it down, it's basically this

0      30.003843
1      25.025562
2      30.567597
3      28.607036
4      27.943524
         ...    
501    23.533341
502    22.375719
503    27.627426
504    26.127967
505    22.344212
Length: 506, dtype: float64

In [11]:
X * lreg.coef_

CRIM        ZN     INDUS  CHAS        NOX         RM       AGE  \
0   -0.000683  0.835568  0.047490   0.0  -9.558437  25.049864  0.045133   
1   -0.002950  0.000000  0.145349   0.0  -8.332541  24.463144  0.054617   
2   -0.002948  0.000000  0.145349   0.0  -8.332541  27.373882  0.042295   
3   -0.003496  0.000000  0.044818   0.0  -8.137108  26.661437  0.031704   
4   -0.007458  0.000000  0.044818   0.0  -8.137108  27.229107  0.037519   
..        ...       ...       ...   ...        ...        ...       ...   
501 -0.006765  0.000000  0.245264   0.0 -10.180268  25.118441  0.047833   
502 -0.004890  0.000000  0.245264   0.0 -10.180268  23.316375  0.053094   
503 -0.006563  0.000000  0.245264   0.0 -10.180268  26.577620  0.062992   
504 -0.011837  0.000000  0.245264   0.0 -10.180268  25.884224  0.061816   
505 -0.005121  0.000000  0.245264   0.0 -10.180268  22.973487  0.055932   

          DIS       RAD       TAX    PTRATIO         B     LSTAT  
0   -6.035068  0.306049 -3.651040 -14.577033  3.695807 -2.613297  
1   -7.329288  0.612099 -2.984972 -16.958901  3.695807 -4.796292  
2   -7.329288  0.612099 -2.984972 -16.958901  3.657909 -2.114776  
3   -8.945181  0.918148 -2.738280 -17.816373  3.674670 -1.542790  
4   -8.945181  0.918148 -2.738280 -17.816373  3.695807 -2.796962  
..        ...       ...       ...        ...       ...       ...  
501 -3.657340  0.306049 -3.367344 -20.007692  3.650087 -5.074414  
502 -3.375359  0.306049 -3.367344 -20.007692  3.695807 -4.764806  
503 -3.198291  0.306049 -3.367344 -20.007692  3.695807 -2.959637  
504 -3.524982  0.306049 -3.367344 -20.007692  3.663682 -3.400434  
505 -3.696295  0.306049 -3.367344 -20.007692  3.695807 -4.135096  

[506 rows x 13 columns]

In [12]:
X.dot(lreg.coef_)
# 'Activation among neurons' is this operation
# How you multiply datasets by each other

0      -6.455645
1     -11.433926
2      -5.891892
3      -7.852452
4      -8.515964
         ...    
501   -12.926148
502   -14.083769
503    -8.832062
504   -10.331522
505   -14.115276
Length: 506, dtype: float64

In [13]:
X = pd.DataFrame(np.random.normal(0, 0.1, 10000).reshape(1000, 10))
# Stepping through the diagram

In [14]:
X.head()

0         1         2         3         4         5         6  \
0  0.057560  0.011926 -0.125551 -0.002381  0.073909  0.002841  0.027009   
1  0.048746 -0.034752  0.119753  0.077192  0.203013 -0.003482  0.020229   
2  0.039837 -0.154400  0.159288 -0.150972 -0.047783 -0.155414 -0.061954   
3  0.184942 -0.081050  0.055110 -0.011039  0.026412  0.183002 -0.020389   
4 -0.026759 -0.039057 -0.004624  0.034928  0.076624  0.050699 -0.031231   

          7         8         9  
0  0.134314 -0.001810  0.042881  
1 -0.001487  0.084882  0.065960  
2 -0.063621 -0.109099 -0.086532  
3 -0.010282 -0.025334 -0.075542  
4  0.234343  0.076857  0.090846

In [16]:
coef1 = np.random.normal(0, 0.1, 200).reshape(10, 20)
bias1 = np.random.normal(0, 0.1, 20)
# When you first start these are typically randomly generated close to 0
# There's a bias unit for every single column of output, which is why there's 20

In [20]:
X_hidden = X.dot(coef1) + bias1

In [25]:
coef2 = np.random.normal(0, 0.1, 20)
bias2 = np.random.normal(0, 0.1)

# For every single coefficient there's a corresponding bias

In [26]:
y = X_hidden.dot(coef2)
# This process is called forward propagation

In [27]:
# When you're training a neural network you're finding the sets of weights at every single internal error


In [28]:
# Neural networks allow you to find nonlinear patterns in nonlinear data
# Linear regression by definition is linear
# In addition to passing it through weights, you have to pass it through an activation function
# The activation function is what makes it non-linear!

In [29]:
X_hidden

0         1         2         3         4         5         6  \
0   -0.063646 -0.073695  0.017848  0.048180 -0.088908 -0.079804 -0.030087   
1   -0.034774 -0.047223 -0.011011  0.026829 -0.066442 -0.084742 -0.034725   
2   -0.024843  0.002834  0.029413  0.030150 -0.079083 -0.053148 -0.032535   
3   -0.052480 -0.048153 -0.006131  0.068329 -0.072196 -0.054109 -0.055323   
4   -0.063823 -0.084543  0.010022  0.049612 -0.122431 -0.063126 -0.007936   
..        ...       ...       ...       ...       ...       ...       ...   
995 -0.039774  0.015122  0.013199  0.051145 -0.136975 -0.096999  0.005935   
996 -0.097742 -0.073581  0.051051  0.062232 -0.149652 -0.081572  0.023933   
997 -0.047927  0.004714  0.050490  0.103138 -0.112130 -0.106492 -0.024613   
998 -0.025506  0.020002 -0.000482  0.080709 -0.101106 -0.104820 -0.008174   
999 -0.062753 -0.071420  0.026538  0.053246 -0.073301 -0.043683 -0.036737   

            7         8         9        10        11        12        13  \
0   -0.042404  0.098984  0.203653  0.107181  0.214551  0.057076 -0.035800   
1   -0.043727  0.054626  0.208382  0.145138  0.193759  0.008034 -0.024561   
2   -0.011253  0.062927  0.191468  0.100093  0.221734  0.009582  0.055638   
3    0.001987  0.073224  0.160698  0.091361  0.216998  0.091735 -0.042701   
4   -0.067031  0.091967  0.203050  0.135823  0.200475  0.014513 -0.042481   
..        ...       ...       ...       ...       ...       ...       ...   
995 -0.041189  0.079531  0.157245  0.090396  0.216192 -0.009790 -0.001675   
996 -0.063305  0.106293  0.194786  0.148321  0.220406  0.021315 -0.044043   
997 -0.006591  0.132644  0.115102  0.043505  0.190657  0.094633 -0.041820   
998 -0.015194  0.098798  0.103976  0.048747  0.173092  0.068993 -0.027431   
999 -0.022206  0.085103  0.169784  0.083276  0.204847  0.074274 -0.041005   

           14        15        16        17        18        19  
0   -0.136982  0.082623 -0.023756 -0.076847  0.124085 -0.108237  
1   -0.171012  0.079969 -0.041847 -0.082468  0.148375 -0.095157  
2   -0.085286  0.066254 -0.004042 -0.105187  0.094042 -0.107440  
3   -0.134582  0.042535  0.004716 -0.083919  0.136495 -0.069561  
4   -0.150035  0.106540 -0.029134 -0.063711  0.146787 -0.100299  
..        ...       ...       ...       ...       ...       ...  
995 -0.100580  0.109646 -0.017187 -0.107054  0.131725 -0.124243  
996 -0.121840  0.126637  0.002889 -0.093511  0.152062 -0.064377  
997 -0.098939  0.095048  0.049072 -0.134828  0.130463 -0.144881  
998 -0.126503  0.099373  0.005417 -0.120723  0.135996 -0.131153  
999 -0.141452  0.065841 -0.002341 -0.084923  0.120539 -0.123422  

[1000 rows x 20 columns]

In [30]:
# If you're dealing with a hidden layer in a neural network, you're almost always going to use the same activation function
np.maximum(0, X_hidden)
# This is it!
# Just take negative numbers and set em to 0
# RELU... rectified linear unit

0         1         2         3    4    5         6         7  \
0    0.0  0.000000  0.017848  0.048180  0.0  0.0  0.000000  0.000000   
1    0.0  0.000000  0.000000  0.026829  0.0  0.0  0.000000  0.000000   
2    0.0  0.002834  0.029413  0.030150  0.0  0.0  0.000000  0.000000   
3    0.0  0.000000  0.000000  0.068329  0.0  0.0  0.000000  0.001987   
4    0.0  0.000000  0.010022  0.049612  0.0  0.0  0.000000  0.000000   
..   ...       ...       ...       ...  ...  ...       ...       ...   
995  0.0  0.015122  0.013199  0.051145  0.0  0.0  0.005935  0.000000   
996  0.0  0.000000  0.051051  0.062232  0.0  0.0  0.023933  0.000000   
997  0.0  0.004714  0.050490  0.103138  0.0  0.0  0.000000  0.000000   
998  0.0  0.020002  0.000000  0.080709  0.0  0.0  0.000000  0.000000   
999  0.0  0.000000  0.026538  0.053246  0.0  0.0  0.000000  0.000000   

            8         9        10        11        12        13   14  \
0    0.098984  0.203653  0.107181  0.214551  0.057076  0.000000  0.0   
1    0.054626  0.208382  0.145138  0.193759  0.008034  0.000000  0.0   
2    0.062927  0.191468  0.100093  0.221734  0.009582  0.055638  0.0   
3    0.073224  0.160698  0.091361  0.216998  0.091735  0.000000  0.0   
4    0.091967  0.203050  0.135823  0.200475  0.014513  0.000000  0.0   
..        ...       ...       ...       ...       ...       ...  ...   
995  0.079531  0.157245  0.090396  0.216192  0.000000  0.000000  0.0   
996  0.106293  0.194786  0.148321  0.220406  0.021315  0.000000  0.0   
997  0.132644  0.115102  0.043505  0.190657  0.094633  0.000000  0.0   
998  0.098798  0.103976  0.048747  0.173092  0.068993  0.000000  0.0   
999  0.085103  0.169784  0.083276  0.204847  0.074274  0.000000  0.0   

           15        16   17        18   19  
0    0.082623  0.000000  0.0  0.124085  0.0  
1    0.079969  0.000000  0.0  0.148375  0.0  
2    0.066254  0.000000  0.0  0.094042  0.0  
3    0.042535  0.004716  0.0  0.136495  0.0  
4    0.106540  0.000000  0.0  0.146787  0.0  
..        ...       ...  ...       ...  ...  
995  0.109646  0.000000  0.0  0.131725  0.0  
996  0.126637  0.002889  0.0  0.152062  0.0  
997  0.095048  0.049072  0.0  0.130463  0.0  
998  0.099373  0.005417  0.0  0.135996  0.0  
999  0.065841  0.000000  0.0  0.120539  0.0  

[1000 rows x 20 columns]

In [33]:
def sigmoid(X):
    return (1 / (np.exp(-X)))

In [37]:
y = X_hidden.dot(coef2)
y

0     -0.026544
1     -0.027626
2     -0.004718
3     -0.029748
4     -0.020515
         ...   
995   -0.007257
996   -0.017142
997   -0.024047
998   -0.025998
999   -0.019110
Length: 1000, dtype: float64

In [36]:
#If you're doing classification...
sigmoid(y)
# Notice how the values change
# The sigmoid function tends to squash values to either 0 or 1 
# SQUASHED

0      0.973806
1      0.972752
2      0.995293
3      0.970690
4      0.979694
         ...   
995    0.992769
996    0.983004
997    0.976240
998    0.974337
999    0.981072
Length: 1000, dtype: float64

In [40]:
import pickle

with open('/Users/aoifeduna/AoifeRepo/aoiferepo/Lectures/Unit4/Class19/data/MNIST/processed/X_train.pkl', 'rb') as X:
    X_train = pickle.load(X)
    
with open('/Users/aoifeduna/AoifeRepo/aoiferepo/Lectures/Unit4/Class19/data/MNIST/processed/y_train.pkl', 'rb') as y:
    y_train = pickle.load(y)

In [42]:
X_train[0]
# This is a list of images
# These are the pixel values! :o

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
         18,  18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,
          0,   0],
       [  

In [43]:
X_train.reshape(60000, 784)

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [44]:
np.unique(y_train)
# These are the unique values in y_train
# The final prediction of y is going to be ten columns
# Each one is going to be a probability that it's one particular class or another

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint8)